import AppKit

/// Polls the general pasteboard for new string content and reports it on the main thread.
final class ClipboardMonitor {
    /// Called on the main thread when a new, non-empty string is copied.
    var onNewText: ((String) -> Void)?

    private var timer: DispatchSourceTimer?
    private var lastChangeCount: Int
    private let pasteboard: NSPasteboard
    private let interval: TimeInterval

    init(pasteboard: NSPasteboard = .general, interval: TimeInterval = 0.5) {
        self.pasteboard = pasteboard
        self.interval = interval
        self.lastChangeCount = pasteboard.changeCount
    }

    deinit { timer?.cancel() }

    func start() {
        stop()
        let t = DispatchSource.makeTimerSource(queue: .main)
        t.schedule(deadline: .now() + interval, repeating: interval)
        t.setEventHandler { [weak self] in self?.poll() }
        t.resume()
        timer = t
    }

    func stop() {
        timer?.cancel()
        timer = nil
    }

    /// Pure capture rule: ignore empty / whitespace-only strings.
    static func isCapturable(_ text: String) -> Bool {
        !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current

        if ClipboardSettings.skipConcealed, isConcealed() { return }
        guard let text = pasteboard.string(forType: .string), Self.isCapturable(text) else { return }
        onNewText?(text)
    }

    /// True when a password manager / transient producer marked the pasteboard.
    private func isConcealed() -> Bool {
        let types = pasteboard.types ?? []
        let flags = [
            "org.nspasteboard.ConcealedType",
            "org.nspasteboard.TransientType",
            "org.nspasteboard.AutoGeneratedType",
        ].map { NSPasteboard.PasteboardType($0) }
        return flags.contains { types.contains($0) }
    }
}
